apiVersion: v1 # String
kind: Pod # String
metadata: # Dictionary
  name: nginx2
  labels: # Dictionary
    app: nginx2  # Key value paids
spec:
  containers: # List
    - name: nginx
      image: nginx
      ports: 
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx2
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx2
